#DATA IMPORT

In [1]:
import pandas as pd
import numpy as np

In [2]:
path_data = '/content/drive/MyDrive/Wile_C/ai4i2020.csv'

data = pd.read_csv(path_data)
print(data)

        UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
0         1     M14860    M                298.1                    308.6   
1         2     L47181    L                298.2                    308.7   
2         3     L47182    L                298.1                    308.5   
3         4     L47183    L                298.2                    308.6   
4         5     L47184    L                298.2                    308.7   
...     ...        ...  ...                  ...                      ...   
9995   9996     M24855    M                298.8                    308.4   
9996   9997     H39410    H                298.9                    308.4   
9997   9998     M24857    M                299.0                    308.6   
9998   9999     H39412    H                299.0                    308.7   
9999  10000     M24859    M                299.0                    308.7   

      Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure

In [3]:
failure = []
for i in range(len(data)):
  if data['Machine failure'][i] == 1:
    failure.append(i)
print(len(failure))

339


In [4]:
X = np.array([data['Air temperature [K]'], data['Process temperature [K]'], data['Rotational speed [rpm]'], data['Torque [Nm]'], data['Tool wear [min]']])
X = np.transpose(X)
print(X.shape)

(10000, 5)


In [5]:
y = np.array(data['Machine failure'])
print(y.shape)

(10000,)


In [6]:
from pandas.core.common import random_state
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(7000, 5) (3000, 5) (7000,) (3000,)


#LINEAR REGRESSION

In [7]:
from sklearn.linear_model import LinearRegression

reg_linear = LinearRegression().fit(X_train, y_train)

In [8]:
reg_linear.score(X_train, y_train)

0.12071606781711175

In [9]:
reg_linear.coef_

array([ 0.02135108, -0.02006165,  0.00051241,  0.01150624,  0.00032186])

In [10]:
predict = reg_linear.predict(X_test)

In [11]:
for i in range(len(predict)):
  if predict[i] < 0.1:
    predict[i] = 0
  else:
    predict[i] = 1
print(predict)

[0. 0. 0. ... 0. 0. 0.]


In [12]:
count = 0
for i in range(len(predict)):
  if predict[i] == y_test[i]:
    count += 1

print(count)

2639


In [13]:
acc = count/len(predict)

In [14]:
print(acc)

0.8796666666666667


In [15]:
failure_test = []
for i in range(len(y_test)):
  if y_test[i] == 1:
    failure_test.append(i)
print(len(failure_test))

93


In [16]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predict))

[[2572  335]
 [  26   67]]


#KNN

In [17]:
from sklearn.neighbors import KNeighborsClassifier

neigh = KNeighborsClassifier(n_neighbors=2)
neigh.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=2)

In [18]:
predict = neigh.predict(X_test)
print(predict)

[0 0 0 ... 0 0 0]


In [19]:
count = 0
for i in range(len(predict)):
  if predict[i] == y_test[i]:
    count += 1

print(count)

2910


In [20]:
acc = count/len(predict)

In [21]:
print(acc)

0.97


In [22]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predict))

[[2900    7]
 [  83   10]]


#RANDOM FOREST

In [23]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier()
clf.fit(X_train, y_train)

RandomForestClassifier()

In [24]:
predict = clf.predict(X_test)
print(predict)

[0 0 0 ... 0 0 0]


In [25]:
count = 0
for i in range(len(predict)):
  if predict[i] == y_test[i]:
    count += 1

print(count)

2957


In [26]:
acc = count/len(predict)

In [27]:
print(acc)

0.9856666666666667


In [28]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predict))

[[2897   10]
 [  33   60]]
